In [1]:
import time
import datetime
import numpy as np
import pandas as pd
# To plot pretty figures
get_ipython().run_line_magic('matplotlib', 'inline')
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
plt.rcParams['axes.labelsize'] = 14
plt.rcParams['xtick.labelsize'] = 12
plt.rcParams['ytick.labelsize'] = 12
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', 1000)
pd.set_option("display.max_colwidth",1000)
pd.set_option('display.width',1000)
import statsmodels.formula.api as sm

In [2]:
import os
filePath = "sample_csv\\"
filename_list=os.listdir(filePath)
print(filename_list)

['20200808.csv', '20201027.csv', '20201031.csv', '20201105.csv', '20201109.csv', '20201117.csv', '20201119.csv', '20201121.csv', '20201127.csv', '20201130.csv', '20201204.csv', '20201208.csv', '20201211.csv', '20201214.csv', '20201217.csv', '20201221.csv', '20201225.csv', '20201229.csv', '20210101.csv', '20210105.csv', '20210109.csv', '20210112.csv', '20210116.csv', '20210119.csv', '20210123.csv', '20210127.csv', '20210201.csv', '20210211.csv', '20210212.csv', '20210216.csv', '20210220.csv', '20210224.csv', '20210228.csv', '20210305.csv', '20210306.csv', '20210311.csv', '20210315.csv', '20210318.csv', '20210321.csv', '20210326.csv', '20210330.csv', '20210407.csv', '20210412.csv', '20210416.csv', '20210420.csv', '20210423.csv', '20210427.csv', '20210429.csv', '20210501.csv', '20210505.csv', '20210507.csv', 'csv_with_date', 'desktop.ini', 'smurf']

In [3]:
dataframe_lists=[]

In [4]:
for file in filename_list:
    if file[-3:]=="csv":
        file_year=file[:4]  #STR
        file_month=file[4:6]
        file_day=file[6:8]
        print("Timestamp="+file_year+"-"+file_month+"-"+file_day)


        df = pd.read_csv(filePath+file,encoding='utf-8')

        armor = ['头部(装甲)', '身体(装甲)','左臂(装甲)', '右臂(装甲)', '左手(装甲)', '右手(装甲)', '左腿(装甲)', '右腿(装甲)']
        body = ['头部(肉体)','身体(肉体)', '左臂(肉体)', '右臂(肉体)', '左手(肉体)', '右手(肉体)', '左腿(肉体)', '右腿(肉体)']
        skeleton = ['头部(骨架)', '身体(骨架)', '左臂(骨架)', '右臂(骨架)', '左手(骨架)', '右手(骨架)', '左腿(骨架)','右腿(骨架)']

        sum_Titian_Boday=df.groupby("泰坦名称").sum()[body]

        grouped=np.where(sum_Titian_Boday==0)
        zero_body=np.array(grouped).tolist()
        #print(zero_body)#first list is for titians, second list is for Armor

        for i in range(len(zero_body[0])):
            print(f"{file}\t{sum_Titian_Boday.index[zero_body[0][i]]}\t不打\t{armor[zero_body[1][i]]}")

Timestamp=2020-08-08
20200808.csv	Lojak	不打	右手(装甲)
20200808.csv	Mohaca	不打	身体(装甲)
20200808.csv	Terro	不打	左臂(装甲)
20200808.csv	Terro	不打	右臂(装甲)
20200808.csv	Terro	不打	左手(装甲)
20200808.csv	Terro	不打	右手(装甲)
20200808.csv	Terro	不打	左腿(装甲)
Timestamp=2020-10-27
20201027.csv	Jukk	不打	头部(装甲)
20201027.csv	Sterl	不打	头部(装甲)
20201027.csv	Sterl	不打	右臂(装甲)
Timestamp=2020-10-31
20201031.csv	Lojak	不打	右臂(装甲)
20201031.csv	Mohaca	不打	身体(装甲)
Timestamp=2020-11-05
20201105.csv	Lojak	不打	右臂(装甲)
20201105.csv	Mohaca	不打	身体(装甲)
Timestamp=2020-11-09
20201109.csv	Jukk	不打	头部(装甲)
20201109.csv	Lojak	不打	右臂(装甲)
Timestamp=2020-11-17
20201117.csv	Jukk	不打	头部(装甲)
20201117.csv	Mohaca	不打	身体(装甲)
20201117.csv	Sterl	不打	头部(装甲)
20201117.csv	Sterl	不打	右臂(装甲)
Timestamp=2020-11-19
20201119.csv	Lojak	不打	右臂(装甲)
20201119.csv	Mohaca	不打	身体(装甲)
Timestamp=2020-11-21
20201121.csv	Mohaca	不打	身体(装甲)
Timestamp=2020-11-27
20201127.csv	Jukk	不打	头部(装甲)
20201127.csv	Terro	不打	右臂(装甲)
Timestamp=2020-11-30
20201130.csv	Jukk	不打	头部(装甲)
20201130.csv	Terro	不打	左臂(装甲)
20201130.csv	Terro	不打	右臂(装甲)
20201130.csv	Terro	不打	右手(装甲)
Timestamp=2020-12-04
20201204.csv	Jukk	不打	头部(装甲)
20201204.csv	Terro	不打	头部(装甲)
20201204.csv	Terro	不打	右臂(装甲)
Timestamp=2020-12-08
20201208.csv	Jukk	不打	头部(装甲)
20201208.csv	Lojak	不打	右臂(装甲)
Timestamp=2020-12-11
20201211.csv	Lojak	不打	右臂(装甲)
20201211.csv	Mohaca	不打	身体(装甲)
Timestamp=2020-12-14
20201214.csv	Lojak	不打	右臂(装甲)
20201214.csv	Mohaca	不打	身体(装甲)
Timestamp=2020-12-17
20201217.csv	Lojak	不打	右臂(装甲)
20201217.csv	Mohaca	不打	身体(装甲)
Timestamp=2020-12-21
20201221.csv	Lojak	不打	右臂(装甲)
20201221.csv	Mohaca	不打	身体(装甲)
Timestamp=2020-12-25
20201225.csv	Jukk	不打	头部(装甲)
20201225.csv	Terro	不打	头部(装甲)
Timestamp=2020-12-29
20201229.csv	Lojak	不打	右臂(装甲)
20201229.csv	Sterl	不打	头部(装甲)
20201229.csv	Sterl	不打	右臂(装甲)
Timestamp=2021-01-01
20210101.csv	Lojak	不打	右臂(装甲)
20210101.csv	Sterl	不打	头部(装甲)
Timestamp=2021-01-05
20210105.csv	Jukk	不打	头部(装甲)
20210105.csv	Terro	不打	头部(装甲)
Timestamp=2021-01-09
20210109.csv	Jukk	不打	头部(装甲)
20210109.csv	Terro	不打	头部(装甲)
Timestamp=2021-01-12
20210112.csv	Jukk	不打	头部(装甲)
20210112.csv	Terro	不打	头部(装甲)
Timestamp=2021-01-16
20210116.csv	Lojak	不打	右臂(装甲)
20210116.csv	Mohaca	不打	身体(装甲)
20210116.csv	Sterl	不打	头部(装甲)
20210116.csv	Sterl	不打	右臂(装甲)
Timestamp=2021-01-19
20210119.csv	Jukk	不打	头部(装甲)
20210119.csv	Lojak	不打	右臂(装甲)
20210119.csv	Mohaca	不打	身体(装甲)
Timestamp=2021-01-23
20210123.csv	Jukk	不打	头部(装甲)
20210123.csv	Terro	不打	头部(装甲)
Timestamp=2021-01-27
20210127.csv	Jukk	不打	头部(装甲)
20210127.csv	Terro	不打	头部(装甲)
20210127.csv	Terro	不打	右臂(装甲)
Timestamp=2021-02-01
20210201.csv	Jukk	不打	头部(装甲)
20210201.csv	Mohaca	不打	身体(装甲)
20210201.csv	Terro	不打	头部(装甲)
20210201.csv	Terro	不打	右臂(装甲)
Timestamp=2021-02-11
20210211.csv	Lojak	不打	右臂(装甲)
20210211.csv	Mohaca	不打	身体(装甲)
20210211.csv	Sterl	不打	头部(装甲)
20210211.csv	Sterl	不打	右臂(装甲)
Timestamp=2021-02-12
20210212.csv	Jukk	不打	头部(装甲)
20210212.csv	Terro	不打	头部(装甲)
20210212.csv	Terro	不打	右臂(装甲)
Timestamp=2021-02-16
20210216.csv	Lojak	不打	右臂(装甲)
20210216.csv	Mohaca	不打	身体(装甲)
20210216.csv	Sterl	不打	头部(装甲)
20210216.csv	Sterl	不打	右臂(装甲)
Timestamp=2021-02-20
20210220.csv	Lojak	不打	右臂(装甲)
20210220.csv	Mohaca	不打	身体(装甲)
20210220.csv	Sterl	不打	头部(装甲)
20210220.csv	Sterl	不打	右臂(装甲)
Timestamp=2021-02-24
20210224.csv	Jukk	不打	身体(装甲)
20210224.csv	Terro	不打	头部(装甲)
20210224.csv	Terro	不打	右臂(装甲)
Timestamp=2021-02-28
20210228.csv	Mohaca the Gale	不打	身体(装甲)
20210228.csv	Terro the Seeker	不打	头部(装甲)
20210228.csv	Terro the Seeker	不打	右臂(装甲)
Timestamp=2021-03-05
20210305.csv	Lojak	不打	右臂(装甲)
20210305.csv	Sterl	不打	头部(装甲)
20210305.csv	Sterl	不打	右臂(装甲)
20210305.csv	Terro	不打	头部(装甲)
20210305.csv	Terro	不打	右臂(装甲)
Timestamp=2021-03-06
20210306.csv	Jukk	不打	头部(装甲)
20210306.csv	Terro	不打	头部(装甲)
20210306.csv	Terro	不打	右臂(装甲)
Timestamp=2021-03-11
20210311.csv	Mohaca the Gale	不打	身体(装甲)
20210311.csv	Terro the Seeker	不打	头部(装甲)
20210311.csv	Terro the Seeker	不打	右臂(装甲)
Timestamp=2021-03-15
20210315.csv	Mohaca	不打	身体(装甲)
20210315.csv	Terro	不打	头部(装甲)
20210315.csv	Terro	不打	右臂(装甲)
Timestamp=2021-03-18
20210318.csv	Jukk	不打	头部(装甲)
20210318.csv	Lojak	不打	右臂(装甲)
Timestamp=2021-03-21
20210321.csv	Jukk	不打	头部(装甲)
20210321.csv	Lojak	不打	右臂(装甲)
Timestamp=2021-03-26
20210326.csv	Jukk	不打	头部(装甲)
20210326.csv	Lojak	不打	右臂(装甲)
20210326.csv	Sterl	不打	头部(装甲)
20210326.csv	Sterl	不打	右臂(装甲)
Timestamp=2021-03-30
20210330.csv	Jukk	不打	头部(装甲)
20210330.csv	Mohaca	不打	身体(装甲)
20210330.csv	Terro	不打	头部(装甲)
20210330.csv	Terro	不打	右臂(装甲)
Timestamp=2021-04-07
20210407.csv	Lojak the Fissure	不打	右臂(装甲)
20210407.csv	Sterl the Unmaker	不打	头部(装甲)
20210407.csv	Sterl the Unmaker	不打	右臂(装甲)
20210407.csv	Terro the Seeker	不打	头部(装甲)
20210407.csv	Terro the Seeker	不打	右臂(装甲)
Timestamp=2021-04-12
20210412.csv	Jukk	不打	头部(装甲)
20210412.csv	Mohaca	不打	身体(装甲)
Timestamp=2021-04-16
20210416.csv	Jukk	不打	头部(装甲)
20210416.csv	Mohaca	不打	身体(装甲)
Timestamp=2021-04-20
20210420.csv	Jukk	不打	头部(装甲)
20210420.csv	Lojak	不打	右臂(装甲)
Timestamp=2021-04-23
20210423.csv	Jukk	不打	头部(装甲)
20210423.csv	Mohaca	不打	身体(装甲)
Timestamp=2021-04-27
20210427.csv	Jukk	不打	头部(装甲)
20210427.csv	Terro	不打	头部(装甲)
20210427.csv	Terro	不打	右臂(装甲)
Timestamp=2021-04-29
20210429.csv	Lojak	不打	右臂(装甲)
Timestamp=2021-05-01
20210501.csv	Jukk	不打	头部(装甲)
Timestamp=2021-05-05
20210505.csv	Jukk	不打	头部(装甲)
20210505.csv	Lojak	不打	右臂(装甲)
Timestamp=2021-05-07
20210507.csv	Jukk	不打	头部(装甲)
20210507.csv	Lojak	不打	右臂(装甲)

In [5]:
header_list = ['PlayerName', 'PlayerCode', 'TotalRaidAttacks', 'TitanNumber', 'TitanName', 'TitanDamage', 'ArmorHead',
               'ArmorTorso', 'ArmorLeftArm', 'ArmorRightArm', 'ArmorLeftHand', 'ArmorRightHand', 'ArmorLeftLeg',
               'ArmorRightLeg',
               'BodyHead', 'BodyTorso', 'BodyLeftArm', 'BodyRightArm', 'BodyLeftHand', 'BodyRightHand', 'BodyLeftLeg',
               'BodyRightLeg', 'SkeletonHead', 'SkeletonTorso', 'SkeletonLeftArm', 'SkeletonRightArm',
               'SkeletonLeftHand',
               'SkeletonRightHand', 'SkeletonLeftLeg', 'SkeletonRightLeg']

In [26]:
df1 = pd.read_csv("sample_csv\\20210507.csv", header=0, names=header_list)

In [27]:
df1['TotalRaidAttacks'].max()

20

In [28]:
df1

    PlayerName PlayerCode  TotalRaidAttacks  TitanNumber TitanName  TitanDamage  ArmorHead  ArmorTorso  ArmorLeftArm  ArmorRightArm  ArmorLeftHand  ArmorRightHand  ArmorLeftLeg  ArmorRightLeg  BodyHead  BodyTorso  BodyLeftArm  BodyRightArm  BodyLeftHand  BodyRightHand  BodyLeftLeg  BodyRightLeg  SkeletonHead  SkeletonTorso  SkeletonLeftArm  SkeletonRightArm  SkeletonLeftHand  SkeletonRightHand  SkeletonLeftLeg  SkeletonRightLeg
0         OSTO    e25yde7                20            0   Takedar     18098110          0     4249708             0              0              0               0             0              0   1255488    6715840      1533767       1130531        688608        1361319      1162844             0             0              0                0                 0                 0                  0                0                 0
1         OSTO    e25yde7                20            1   Takedar            0          0           0             0              0              0               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0
2         OSTO    e25yde7                20            2      Jukk     19218242          0           0             0              0              0               0             0              0         0    1844741      1096022       1245824        985381         918034      5879375       7248862             0              0                0                 0                 0                  0                0                 0
3         OSTO    e25yde7                20            3      Jukk     19349413       3984           0             0         692508              0               0             0              0         0    6637156      1069809       7758546        954661        1124146       376840        731758             0              0                0                 0                 0                  0                0                 0
4         OSTO    e25yde7                20            4     Lojak            0          0           0             0              0              0               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0
..         ...        ...               ...          ...       ...          ...        ...         ...           ...            ...            ...             ...           ...            ...       ...        ...          ...           ...           ...            ...          ...           ...           ...            ...              ...               ...               ...                ...              ...               ...
387      一个复古风    y66xd7n                 8            3      Jukk            0          0           0             0              0              0               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0
388      一个复古风    y66xd7n                 8            4     Lojak            0          0           0             0              0              0               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0
389      一个复古风    y66xd7n                 8            5   Takedar            0          0           0             0              0              0               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0
390      一个复古风    y66xd7n                 8            6     Lojak      6112856          0           0        671270              0        5441586               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0
391      一个复古风    y66xd7n                 8            7   Takedar            0          0           0             0              0              0               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0

[392 rows x 30 columns]

In [23]:
df1['TitanNumber'].max()

7

In [31]:
df1.groupby("PlayerCode").count().shape[0]

49

In [44]:
bodys=['BodyHead', 'BodyTorso', 'BodyLeftArm', 'BodyRightArm', 'BodyLeftHand', 'BodyRightHand', 'BodyLeftLeg', 'BodyRightLeg']

In [54]:
no_attacks=df1.groupby(['TitanNumber','TitanName'])[bodys].sum()
no_attacks=no_attacks.reset_index()
no_attacks

   TitanNumber TitanName  BodyHead  BodyTorso  BodyLeftArm  BodyRightArm  BodyLeftHand  BodyRightHand  BodyLeftLeg  BodyRightLeg
0            0   Takedar  48052003   38572177      6373005       6949554       8436379        7288511      9541273      10949995
1            1   Takedar  40286989   51422452      8059509       9124995       9124998        7353175      9674963      10949986
2            2      Jukk         0   51099979     10229986      12208451      12774992       10137546     24856800      24700963
3            3      Jukk         0   51099979     12774990      12616788      11003234        8095024     25549983      25549987
4            4     Lojak  26697863   54985403     10563686             0       9592932        6119907     16868868      21713677
5            5   Takedar  28178008   59819487      9124987       9124990       9124991        9124992     13966632      11274778
6            6     Lojak  22493357   46845119     10949991             0      10949990       10949988     21899993      21899988
7            7   Takedar  36912940   52436974      9712435       9124984      11374878        9316922     10949981      10949984

In [57]:
df1

    PlayerName PlayerCode  TotalRaidAttacks  TitanNumber TitanName  TitanDamage  ArmorHead  ArmorTorso  ArmorLeftArm  ArmorRightArm  ArmorLeftHand  ArmorRightHand  ArmorLeftLeg  ArmorRightLeg  BodyHead  BodyTorso  BodyLeftArm  BodyRightArm  BodyLeftHand  BodyRightHand  BodyLeftLeg  BodyRightLeg  SkeletonHead  SkeletonTorso  SkeletonLeftArm  SkeletonRightArm  SkeletonLeftHand  SkeletonRightHand  SkeletonLeftLeg  SkeletonRightLeg
0         OSTO    e25yde7                20            1   Takedar            0          0           0             0              0              0               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0
1         OSTO    e25yde7                20            2      Jukk     19218242          0           0             0              0              0               0             0              0         0    1844741      1096022       1245824        985381         918034      5879375       7248862             0              0                0                 0                 0                  0                0                 0
2         OSTO    e25yde7                20            3      Jukk     19349413       3984           0             0         692508              0               0             0              0         0    6637156      1069809       7758546        954661        1124146       376840        731758             0              0                0                 0                 0                  0                0                 0
3         OSTO    e25yde7                20            4     Lojak            0          0           0             0              0              0               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0
4         OSTO    e25yde7                20            5   Takedar            0          0           0             0              0              0               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0
..         ...        ...               ...          ...       ...          ...        ...         ...           ...            ...            ...             ...           ...            ...       ...        ...          ...           ...           ...            ...          ...           ...           ...            ...              ...               ...               ...                ...              ...               ...
386      一个复古风    y66xd7n                 8            3      Jukk            0          0           0             0              0              0               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0
387      一个复古风    y66xd7n                 8            4     Lojak            0          0           0             0              0              0               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0
388      一个复古风    y66xd7n                 8            5   Takedar            0          0           0             0              0              0               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0
389      一个复古风    y66xd7n                 8            6     Lojak      6112856          0           0        671270              0        5441586               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0
390      一个复古风    y66xd7n                 8            7   Takedar            0          0           0             0              0              0               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0

[391 rows x 30 columns]

In [56]:
def add_new_CSVRules_instance(row):
    
    global each_csv_instances
    global player_name_t_new_instances
    body_TF=[True,True,True,True,True,True,True,True]
    body=['BodyHead', 'BodyTorso', 'BodyLeftArm', 'BodyRightArm', 'BodyLeftHand', 'BodyRightHand', 'BodyLeftLeg', 'BodyRightLeg']
    for i in range(len(body)):
        if row[body[i]]<=5000000:
            body_TF[i]=False
            
    if body_TF==[True,True,True,True,True,True,True,True]:
        return
    
    CSVRules_t_new_instance = CSVRules(      
        TitanNumber =row['TitanNumber'] ,
        TitanName =row['TitanName'] ,
        CSV_ID=csv_id,
        ArmorHead = body_TF[0],
        ArmorTorso = body_TF[1],
        ArmorLeftArm = body_TF[2],
        ArmorRightArm = body_TF[3],
        ArmorLeftHand = body_TF[4],
        ArmorRightHand = body_TF[5],
        ArmorLeftLeg = body_TF[6],
        ArmorRightLeg = body_TF[7],
    )

    each_csv_instances.append(player_name_t_new_instance)


no_attacks.apply(add_new_CSVRules_instance, axis=1, args=())

NameError: name 'CSVRules' is not defined

In [59]:
df=df1.copy()

In [60]:
df.columns

Index(['PlayerName', 'PlayerCode', 'TotalRaidAttacks', 'TitanNumber', 'TitanName', 'TitanDamage', 'ArmorHead', 'ArmorTorso', 'ArmorLeftArm', 'ArmorRightArm', 'ArmorLeftHand', 'ArmorRightHand', 'ArmorLeftLeg', 'ArmorRightLeg', 'BodyHead', 'BodyTorso', 'BodyLeftArm', 'BodyRightArm', 'BodyLeftHand', 'BodyRightHand', 'BodyLeftLeg', 'BodyRightLeg', 'SkeletonHead', 'SkeletonTorso', 'SkeletonLeftArm', 'SkeletonRightArm', 'SkeletonLeftHand', 'SkeletonRightHand', 'SkeletonLeftLeg', 'SkeletonRightLeg'], dtype='object')

In [61]:


armor = ['ArmorHead', 'ArmorTorso', 'ArmorLeftArm', 'ArmorRightArm', 'ArmorLeftHand', 'ArmorRightHand', 'ArmorLeftLeg', 'ArmorRightLeg']
body = ['BodyHead', 'BodyTorso', 'BodyLeftArm', 'BodyRightArm', 'BodyLeftHand', 'BodyRightHand', 'BodyLeftLeg', 'BodyRightLeg']
skeleton = ['SkeletonHead', 'SkeletonTorso', 'SkeletonLeftArm', 'SkeletonRightArm', 'SkeletonLeftHand', 'SkeletonRightHand', 'SkeletonLeftLeg', 'SkeletonRightLeg']

sum_Titian_Boday=df.groupby("TitanName").sum()[body]

In [62]:
sum_Titian_Boday

            BodyHead  BodyTorso  BodyLeftArm  BodyRightArm  BodyLeftHand  BodyRightHand  BodyLeftLeg  BodyRightLeg
TitanName
Jukk               0  102199958     23004976      24825239      23778226       18232570     50406783      50250950
Lojak       49191220  101830522     21513677             0      20542922       17069895     38768861      43613665
Takedar    153429940  202251090     33269936      34324523      38061246       33083600     44132849      44124743

In [63]:
grouped=np.where(sum_Titian_Boday==0)

In [64]:
grouped

(array([0, 1], dtype=int64), array([0, 3], dtype=int64))

In [66]:
zero_body=np.array(grouped).tolist()
zero_body

[[0, 1], [0, 3]]

In [67]:
list_sum_Titian_Boday_index=list(sum_Titian_Boday.index)
list_sum_Titian_Boday_index

['Jukk', 'Lojak', 'Takedar']

In [ ]:
list_sum_Titian_Boday_index=list(sum_Titian_Boday.index)
#print(list_sum_Titian_Boday_index)

titian_need_Zero=[]
for i in range(len(zero_body[0])):
    titian_need_Zero.append(list_sum_Titian_Boday_index[zero_body[0][i]])
#print(titian_need_Zero)

def wrong_function(row):
    #print(row['泰坦名称'])
    #print("===========================")
    if str(row['泰坦名称']) in titian_need_Zero:
        #print("我进if啦==================================================")
        num_titian=list_sum_Titian_Boday_index.index(row['泰坦名称'])
        #print(f"我是第{num_titian}个泰坦")
        wrong_dmg=0
        #遍历zero_body[0]，如果和num_titian一样，就累加，遍历结束，返回
        for i in range(len(zero_body[0])):
            if num_titian==i:
                wrong_dmg += row[armor[zero_body[1][i]]]
                #print(wrong_dmg)
        return wrong_dmg
    else:
        return 0



df["错误伤害"]=df.apply(wrong_function,axis=1,args=())

df["有效伤害"]=df["泰坦伤害"]-df["错误伤害"]

df_total=df.groupby(["玩家编号","玩家名称"]).sum()
df_total["突袭次数"]=df.groupby(["玩家编号","玩家名称"])["总突击伤害"].mean()
df_total["个人均伤"]=df_total["泰坦伤害"]/df_total["突袭次数"]
df_total["有效占比"]=round(df_total["有效伤害"]/df_total["泰坦伤害"]*100,2)

df_total['armor_total'] = round(df_total[armor].apply(lambda x : (x.sum()),axis=1 ),2)

df_total['body_total'] = round(df_total[body].apply(lambda x : (x.sum()),axis=1 ),2)

df_total['armor_total_per']=round((df_total['armor_total']/df_total["泰坦伤害"])*100,2)

df_total['body_total_per']=round((df_total['body_total']/df_total["泰坦伤害"])*100,2)

df_total["Rank_有效伤害"]=df_total["有效伤害"].rank(ascending=False).map(lambda x:int(x))
df_total["Rank_倒数次数"]=df_total["总突击伤害"].rank(ascending=True).map(lambda x:int(x))

df_f=df_total.drop(columns=['总突击伤害',"泰坦编号",'头部(装甲)', '身体(装甲)','左臂(装甲)', '右臂(装甲)', '左手(装甲)', '右手(装甲)', '左腿(装甲)', '右腿(装甲)',
                       '头部(肉体)','身体(肉体)', '左臂(肉体)', '右臂(肉体)', '左手(肉体)', '右手(肉体)', '左腿(肉体)', '右腿(肉体)',
                       '头部(骨架)', '身体(骨架)', '左臂(骨架)', '右臂(骨架)', '左手(骨架)', '右手(骨架)', '左腿(骨架)','右腿(骨架)' ])


list_columns_temp=list(df_f.columns)

timestamp=pd.Timestamp(file_year+"-"+file_month+"-"+file_day)

df_f.columns=[[timestamp]*len(list(df_f.columns)),list_columns_temp]


dataframe_lists.append(df_f)

In [70]:
df.groupby(["PlayerCode","TitanNumber"]).sum().reset_index()

    PlayerCode  TitanNumber  TotalRaidAttacks  TitanDamage  ArmorHead  ArmorTorso  ArmorLeftArm  ArmorRightArm  ArmorLeftHand  ArmorRightHand  ArmorLeftLeg  ArmorRightLeg  BodyHead  BodyTorso  BodyLeftArm  BodyRightArm  BodyLeftHand  BodyRightHand  BodyLeftLeg  BodyRightLeg  SkeletonHead  SkeletonTorso  SkeletonLeftArm  SkeletonRightArm  SkeletonLeftHand  SkeletonRightHand  SkeletonLeftLeg  SkeletonRightLeg
0      2ww84em            0                13            0          0           0             0              0              0               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0
1      2ww84em            1                13            0          0           0             0              0              0               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0
2      2ww84em            2                13            0          0           0             0              0              0               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0
3      2ww84em            3                13     20406253     527212    11597502        661444         418191         725952          543056       5555780         377113         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0
4      2ww84em            4                13            0          0           0             0              0              0               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0
..         ...          ...               ...          ...        ...         ...           ...            ...            ...             ...           ...            ...       ...        ...          ...           ...           ...            ...          ...           ...           ...            ...              ...               ...               ...                ...              ...               ...
386    yg8x58q            3                20            0          0           0             0              0              0               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0
387    yg8x58q            4                20     13719165    5852463      799935        579249              0         657167          929417        868225        4032705         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0
388    yg8x58q            5                20     13508558          0     7305675        268546        3175721         452449         1338956             0              0    238683          0            0             0             0              0       310381        418144             0              0                0                 0                 0                  0                0                 0
389    yg8x58q            6                20            0          0           0             0              0              0               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0
390    yg8x58q            7                20     13732434          0     8108677             0              0              0               0             0              0    872567          0       794407        764824        733530         894865       646080        917480             0              0                0                 0                 0                  0                0                 0

[391 rows x 28 columns]

In [ ]:
df['WrongDMG']

In [71]:
parts_sign=[[True, True, False, False, False, False, False, True, 0], [True, False, True, True, True, True, True, True, 1], [True, True, True, True, True, False, True, True, 2], [True, False, True, True, True, True, True, True, 3], [True, False, True, True, True, True, True, True, 4], [True, True, True, True, True, False, True, True, 5]]

In [ ]:
for i in parts_sign:
    if row['TitanNumber']==i[8]:
        for j in range(len(i)):
            if i[j]==False:

In [ ]:
def get_WrongDMG(row):
    armor=['ArmorHead','ArmorTorso', 'ArmorLeftArm', 'ArmorRightArm', 'ArmorLeftHand', 'ArmorRightHand', 'ArmorLeftLeg','ArmorRightLeg']
    WrongDMG_per_titan=0
    for i in parts_sign:
        if row['TitanNumber']==i[8]:
            for j in range(len(i)):
                if i[j]==False:
                    WrongDMG_per_titan+=row[armor[j]]
    return WrongDMG_per_titan

In [25]:
df1

    PlayerName PlayerCode  TotalRaidAttacks  TitanNumber TitanName  TitanDamage  ArmorHead  ArmorTorso  ArmorLeftArm  ArmorRightArm  ArmorLeftHand  ArmorRightHand  ArmorLeftLeg  ArmorRightLeg  BodyHead  BodyTorso  BodyLeftArm  BodyRightArm  BodyLeftHand  BodyRightHand  BodyLeftLeg  BodyRightLeg  SkeletonHead  SkeletonTorso  SkeletonLeftArm  SkeletonRightArm  SkeletonLeftHand  SkeletonRightHand  SkeletonLeftLeg  SkeletonRightLeg
0         OSTO    e25yde7                20            1   Takedar            0          0           0             0              0              0               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0
1         OSTO    e25yde7                20            2      Jukk     19218242          0           0             0              0              0               0             0              0         0    1844741      1096022       1245824        985381         918034      5879375       7248862             0              0                0                 0                 0                  0                0                 0
2         OSTO    e25yde7                20            3      Jukk     19349413       3984           0             0         692508              0               0             0              0         0    6637156      1069809       7758546        954661        1124146       376840        731758             0              0                0                 0                 0                  0                0                 0
3         OSTO    e25yde7                20            4     Lojak            0          0           0             0              0              0               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0
4         OSTO    e25yde7                20            5   Takedar            0          0           0             0              0              0               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0
..         ...        ...               ...          ...       ...          ...        ...         ...           ...            ...            ...             ...           ...            ...       ...        ...          ...           ...           ...            ...          ...           ...           ...            ...              ...               ...               ...                ...              ...               ...
386      一个复古风    y66xd7n                 8            3      Jukk            0          0           0             0              0              0               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0
387      一个复古风    y66xd7n                 8            4     Lojak            0          0           0             0              0              0               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0
388      一个复古风    y66xd7n                 8            5   Takedar            0          0           0             0              0              0               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0
389      一个复古风    y66xd7n                 8            6     Lojak      6112856          0           0        671270              0        5441586               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0
390      一个复古风    y66xd7n                 8            7   Takedar            0          0           0             0              0              0               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0

[391 rows x 30 columns]

In [13]:
df1.groupby("PlayerCode").sum().reset_index()

   PlayerCode  TotalRaidAttacks  TitanNumber  TitanDamage  ArmorHead  ArmorTorso  ArmorLeftArm  ArmorRightArm  ArmorLeftHand  ArmorRightHand  ArmorLeftLeg  ArmorRightLeg  BodyHead  BodyTorso  BodyLeftArm  BodyRightArm  BodyLeftHand  BodyRightHand  BodyLeftLeg  BodyRightLeg  SkeletonHead  SkeletonTorso  SkeletonLeftArm  SkeletonRightArm  SkeletonLeftHand  SkeletonRightHand  SkeletonLeftLeg  SkeletonRightLeg
0     2ww84em               104           28     66254639   16742392    24470767       1737261        1025945        1183892         1786267      15344190        3539870         0          0            0             0         57696              0       237653        128697             0              0                0                 0                 0                  0                0                 0
1     3239p74               128           28     45838981    2292998     1892306        362821         269083        3073846         2850674       4143555         618881   2346580   10312445      5146069        226098        726386        3069252      1170286       7337019             0              0                0               222               343                  0                0               101
2     32d47b9               160           28     76583628   20647320     9243547        154917        8608791         351339         3729808       4040027        6201297   4265865   13644866      1286181             0        209663        2283130      1112654        804204             0              0                0                 0                 0                  0                0                 0
3     3nw4q8n                64           28     29444615     114831     7747533       1022282              0          59178           78852       3094895        2014173         0    9362672            0             0       4364294              0      1585901             0             0              0                0                 0                 0                  0                0                 0
4     459k745                96           28     24336773   10338114     1670146       7627127          17830        1421188           20196       1664023         431505         0          0       355868             0        579709         211058            0             0             0              0                0                 0                 0                  0                0                 0
5     523dqmp               128           28     73280041     586201     1288465       5241511         492102        5271505          965196       1244585        1083431  20880940   17909384      2820531        465584       1107554        6419441      6567793        935803             0              0                0                 0                 0                  0                0                 0
6     52ymnnk               128           28     55467114        906     7906850        562275         874141       12895222         1220804       1265461        1216414   9299582    2710021      1671402       2952755       8499522        2108183      1282936        999933             0              0                0                 0               687                  0                0                 0
7     5kmer69               128           28     48655115     896058    17837779       1229438          26716        1916747         4847209       1736053        5062340   1359315    7336803      3388255         27607       1055594         120119       982208        832799             0              0                0                 0                55                  0                0                 0
8     6567qp8               160           28     70293381    8634152    10890774       5367047         964151        1026253         1583019       5170400        4701135  11329144    9270311      3673897       1336877       1820121        2140222      1698665        687073             0              0                0                 0                 0                  0                0               123
9     65eqmym               128           28     37749642    1789542     1509476             0              0              0            2133       2353750        3688317         0    4754951       912268       1521986       4364423              0      7166056       9686198             0              0                0                 0                 0                  0              389               146
10    65yxpe2               128           28     30327035          0     7491764        400820         173447         776580          610443             0              0   4722282    5446661       535333       1356395        595223         409869       464606       7337170             0              0                0              6385                 0                 46                0                 0
11    6r922bx                64           28     31258244       4623    18982066             0            332              0          950562        410326         390921       997    4484398       430327        575781       1438641         865686      1324388       1399189             0              0                0                 0                 0                  0                0                 0
12    72qkpqp               128           28     27840203      58884     2661493        704959        5147296         315349         2279440       1797134         200655    726466    5614338       665568       2171533        144922        2096792      2595667        659654             0              0                0                 0                41                  0                0                 0
13    7nr6628               160           28     70184422   22433637    12874168       1551922         354399         901027         1109594        881333        1039900  17678437    6721072       926620        981589        135306         998647      1106210        490547             0              0                0                 0                 0                  0                0                 0
14    87ee6rw                88           28     37475493    5022600    12073342             0         333743         456115          891132       4866537              0         0    6537058       312806             0             0        6417747       197666        366741             0              0                0                 0                 0                  0                0                 0
15    9wnm53d               160           28     47075542    4278214     4937060        410695         252952        2625483         1128816       5786622         258505   1651613    8041333       829670        540823       2824459         352045      5388957       7764421             0              0             1660                 0              2065                  0              132                 0
16    b2rmkk3               128           28     65017920    8642808    12443949        105810          94416        2406160          121139        865817        3294951  12935082   12805291       381562        466676         21347         605260      3568069       6259213             0              0                0                 0                71                  0                0               286
17    b65mrx8                96           28     47194022    2637700     5073873       2865623        2100328        5775004         8993697       2543122       12952614         0          0            0             0             0              0      4252051             0             0              0                0                 0                 0                  0                0                 0
18    b6667p5               160           28     76192439     596399    13963813      10831909        1854896        3382547         4630790             0          43823   4445452   15026492      6234421       3053885       1698325        3627753      1424867       5370784             0              0                0                 0                 0                  0                0              6267
19    d234wb5               128           28     57452573   15283703     6380392        125926        1034495        2406343         2646099       8560116        3465674   7493901    6241260       584370       1197433        511892        1418085            0         99327             0              0             3140                 0               157                252                0                 0
20    d2w2qe2                64           28     20030190    5265019     2010343             0              0              0               0             0              0   7589490      30195      2144451             0             0              0            0       2990691             0              0                0                 0                 0                  0                0                 0
21    d55nkr9               128           28     36982061    3644605      941850        756781        1014710         815874         4332937       3456155        5226052   7210071     856321       831195        705061       2586333         702049      2960726        941326             0              0                0                 0                 0                  0                0                 0
22    de99k4r                96           28     40254785    3055715    13171606             0              0              0               0       7449811        2623964         0    2686181      2909146             0             0              0      4382895       3975463             0              0                0                 0                 0                  0                0                 0
23    e25yde7               140           28     77038353       3984     7118660       6921176         692508              0               0        771474              0   3074937   20039882      4004118       9760029       2805000        4068673      8075659       9702081             0              0                0                 0               156                  0                0                 0
24    e4eyrwg               128           28     28391501    1781614     6614667             0              0              0               0        729633         866041   1821909   11062801            0             0             0              0      2195892       3317912             0              0                0                 0                 0                  0             1026                 0
25    e4w4gp8                96           28     31885076    3726716     2122314       5935900         572666        2173959          638732       6279152        1469998   6115219    2344917       261298             0        244193              0            0             0             0              0                0                 0                 0                  0                0                 0
26    g8d49rg               128           28     27406777    1263926     9836582       1686987        3126982        1057554         2253860             0              0         0    2154300            0       1526631             0        1201792      1516537       1780923             0            595                0                 0                98                  0                0                 0
27    gmyr876               152           28     78168767   28309797     4478420        395650         418779        1011377          318145       5176586        9954126   5817250    2781503       658015        677096       4814730        5397204       537343       7422666             0              0                0                 0                65                  0                0                 0
28    md4enrk               128           28     38419623    7758092     1530629        690488        1284864        3731016          902035        135808         296210   6112164    4066473       614205             0        403868         430198      9748393        715066             0              0                0                 0                 0                  0                0               100
29    mng2634               112           28     60396797          0    11199637       5304545              0              0               0        214633       10564389     15437   11528493      6087043             0             0         142623      9949281       5376555             0              0              366                 0             11532               2258                0                 0
30    ng64n3n                64           28     41459889          0           0             0        1550508              0         2202433             0              0   1373139    9813512      2575698       7409107       2024825        2854000      7883150       3773199             0              0                0                 0               309                  0                0                 0
31    ny32m8q               104           28     40866495      35120    15158058       1288444        1430721        1452212         4402855             0       10742431     55772    3699278       301891             0         53727              0        96386       2149589             0              0                0                 0                 0                  0                0                 0
32     p2dbk3               128           28     60131580    1387436    16679885        469258         425640         287672          298025        392315         339640   1269849   24837235      1089358       1326219        906252        1150429      1111396       8160745             0            176                0                 0                 0                  0                0                35
33    p5k6p4k               128           28     30883086    1893054     5547850        766574              0         327467          768511       1292863        4074157   3774223    7115687       820181       1048472       1163634         917073       875222        498051             0              0                0                 0                 0                  0                0                51
34    p7dygdn               128           28     53730886    6613482     2718679       1636961        5117398        2168053         1792181       6001803        9679612    506174    4865082      7116727       1579780       2652154         678847       603292             0             0              0              584                 0                 0                  0                0                64
35    p7k86mx               128           28     64223476    3972138    17948642       2088259        8177366        3688363         4837480       1096291         660883   5796532   10098513      1353570        376774        626844         386762      2000568       1113004             0              0                0                 0              1473                  0                0                 0
36    p7qkn7y                96           28     50932037   14263888    17108400       1493270        1795111         734739         1199247         74824         555041   4286999    7426446       399554             0             0         387468       317565        889474             0              0                0                 0                 0                  0                0                 0
37    pgrbxby               160           28     59945411    8491477    12391030        785332        1544790        1490421         7340401       3354444         738377   2509218   10105631      1857783       1399944       4706950        1242741      1948188         38670             0              0                0                 0                 0                  0                0                 0
38    pmy9pbd                64           28     29275886    8916308           0             0              0              0               0             0              0   3893086   11611704       185970       1222321             0         487281      2959212             0             0              0                0                 0                 0                  0                0                 0
39    qq3k69r               160           28     53035547     344617    21727453        882522         664710         570044         1076192       3737701         585241    839548   17980742      1070311        270981       1063147         501300       744424        976596             0              0                0                 0                 0                  0                0                 0
40    qq52rrr               160           28     64858054    5146741    20859986       2826879         797210        1439854         1326688        359474         338796   7269357   16960963       823386        581116        288368        3552924       902448       1380997             0           2659                0                 0                55                  0              138                 0
41    r563kb9               128           28     49818247    1554075     7331590       6894289        6046134        7999347         3732535       2198120        1542993    786095     262901      1598928        342036        840503        3171806       888787       4627575             0              0                0                 0                 0                  0                0               516
42    r5xpnx5               128           28     52748498    2484957     2397114             0              0              0            4916       3589017        5721530         0    7414467      1470716       2086263       6154730              0      8965411      12454147             0              0                0                 0                 0                  0             3802              1421
43    rq79w8n               128           28     73428537    5601525     4609067        274483        1179539         877472         6350826       3202287              0   7654987   23865348       687589             0        455573         720110      8273246       9676472             0              0                0                 0                 0                  0                0                 0
44    x67y9yq               128           28     57888330   15406429     6353871             0              0         610071               0       4206767              0   8371449   11129767      4803639             0       7002730              0            0             0             0              0                0                 0              3599                  0                0                 0
45    xnxdx22               128           28     93490687    1092716    19688233        705085        2196168         136175          598277             0              0  10618597   34341159      2010376      10428065       3575228        2122429      3454306       2509081             0              0               39             11944              2635                157                0                 0
46    y66xd7n                64           28     17437390          0           0        671270         291608        6834147               0             0              0     28917      16483       373850             0       9124998          30376        20251         44552             0              0                0                 0               936                  0                0                 0

In [20]:
df1[df1["PlayerCode"]=="x67y9yq"]['TotalRaidAttacks'].max()

16

In [30]:
(df1['TitanNumber'].max()+1)

8