In [1]:
import time
import datetime
import numpy as np
import pandas as pd
# To plot pretty figures
get_ipython().run_line_magic('matplotlib', 'inline')
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
plt.rcParams['axes.labelsize'] = 14
plt.rcParams['xtick.labelsize'] = 12
plt.rcParams['ytick.labelsize'] = 12
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', 1000)
pd.set_option("display.max_colwidth",1000)
pd.set_option('display.width',1000)
import statsmodels.formula.api as sm

In [2]:
import os
filePath = "sample_csv\\"
filename_list=os.listdir(filePath)
print(filename_list)

['20200808.csv', '20201027.csv', '20201031.csv', '20201105.csv', '20201109.csv', '20201117.csv', '20201119.csv', '20201121.csv', '20201127.csv', '20201130.csv', '20201204.csv', '20201208.csv', '20201211.csv', '20201214.csv', '20201217.csv', '20201221.csv', '20201225.csv', '20201229.csv', '20210101.csv', '20210105.csv', '20210109.csv', '20210112.csv', '20210116.csv', '20210119.csv', '20210123.csv', '20210127.csv', '20210201.csv', '20210211.csv', '20210212.csv', '20210216.csv', '20210220.csv', '20210224.csv', '20210228.csv', '20210305.csv', '20210306.csv', '20210311.csv', '20210315.csv', '20210318.csv', '20210321.csv', '20210326.csv', '20210330.csv', '20210407.csv', '20210412.csv', '20210416.csv', '20210420.csv', '20210423.csv', '20210427.csv', '20210429.csv', '20210501.csv', '20210505.csv', '20210507.csv', 'csv_with_date', 'desktop.ini', 'smurf']

In [3]:
dataframe_lists=[]

In [4]:
for file in filename_list:
    if file[-3:]=="csv":
        file_year=file[:4]  #STR
        file_month=file[4:6]
        file_day=file[6:8]
        print("Timestamp="+file_year+"-"+file_month+"-"+file_day)


        df = pd.read_csv(filePath+file,encoding='utf-8')

        armor = ['头部(装甲)', '身体(装甲)','左臂(装甲)', '右臂(装甲)', '左手(装甲)', '右手(装甲)', '左腿(装甲)', '右腿(装甲)']
        body = ['头部(肉体)','身体(肉体)', '左臂(肉体)', '右臂(肉体)', '左手(肉体)', '右手(肉体)', '左腿(肉体)', '右腿(肉体)']
        skeleton = ['头部(骨架)', '身体(骨架)', '左臂(骨架)', '右臂(骨架)', '左手(骨架)', '右手(骨架)', '左腿(骨架)','右腿(骨架)']

        sum_Titian_Boday=df.groupby("泰坦名称").sum()[body]

        grouped=np.where(sum_Titian_Boday==0)
        zero_body=np.array(grouped).tolist()
        #print(zero_body)#first list is for titians, second list is for Armor

#         for i in range(len(zero_body[0])):
#             print(f"{file}\t{sum_Titian_Boday.index[zero_body[0][i]]}\t不打\t{armor[zero_body[1][i]]}")

Timestamp=2020-08-08
Timestamp=2020-10-27
Timestamp=2020-10-31
Timestamp=2020-11-05
Timestamp=2020-11-09
Timestamp=2020-11-17
Timestamp=2020-11-19
Timestamp=2020-11-21
Timestamp=2020-11-27
Timestamp=2020-11-30
Timestamp=2020-12-04
Timestamp=2020-12-08
Timestamp=2020-12-11
Timestamp=2020-12-14
Timestamp=2020-12-17
Timestamp=2020-12-21
Timestamp=2020-12-25
Timestamp=2020-12-29
Timestamp=2021-01-01
Timestamp=2021-01-05
Timestamp=2021-01-09
Timestamp=2021-01-12
Timestamp=2021-01-16
Timestamp=2021-01-19
Timestamp=2021-01-23
Timestamp=2021-01-27
Timestamp=2021-02-01
Timestamp=2021-02-11
Timestamp=2021-02-12
Timestamp=2021-02-16
Timestamp=2021-02-20
Timestamp=2021-02-24
Timestamp=2021-02-28
Timestamp=2021-03-05
Timestamp=2021-03-06
Timestamp=2021-03-11
Timestamp=2021-03-15
Timestamp=2021-03-18
Timestamp=2021-03-21
Timestamp=2021-03-26
Timestamp=2021-03-30
Timestamp=2021-04-07
Timestamp=2021-04-12
Timestamp=2021-04-16
Timestamp=2021-04-20
Timestamp=2021-04-23
Timestamp=2021-04-27
Timestamp=2021-04-29
Timestamp=2021-05-01
Timestamp=2021-05-05
Timestamp=2021-05-07

In [5]:
header_list = ['PlayerName', 'PlayerCode', 'TotalRaidAttacks', 'TitanNumber', 'TitanName', 'TitanDamage', 'ArmorHead',
               'ArmorTorso', 'ArmorLeftArm', 'ArmorRightArm', 'ArmorLeftHand', 'ArmorRightHand', 'ArmorLeftLeg',
               'ArmorRightLeg',
               'BodyHead', 'BodyTorso', 'BodyLeftArm', 'BodyRightArm', 'BodyLeftHand', 'BodyRightHand', 'BodyLeftLeg',
               'BodyRightLeg', 'SkeletonHead', 'SkeletonTorso', 'SkeletonLeftArm', 'SkeletonRightArm',
               'SkeletonLeftHand',
               'SkeletonRightHand', 'SkeletonLeftLeg', 'SkeletonRightLeg']

In [6]:
df1 = pd.read_csv("sample_csv\\20210507.csv", header=0, names=header_list)

In [9]:
from connection_dbModel import *

In [20]:
df1

    PlayerName PlayerCode  TotalRaidAttacks  TitanNumber TitanName  TitanDamage  ArmorHead  ArmorTorso  ArmorLeftArm  ArmorRightArm  ArmorLeftHand  ArmorRightHand  ArmorLeftLeg  ArmorRightLeg  BodyHead  BodyTorso  BodyLeftArm  BodyRightArm  BodyLeftHand  BodyRightHand  BodyLeftLeg  BodyRightLeg  SkeletonHead  SkeletonTorso  SkeletonLeftArm  SkeletonRightArm  SkeletonLeftHand  SkeletonRightHand  SkeletonLeftLeg  SkeletonRightLeg
0         OSTO    e25yde7                20            0   Takedar     18098110          0     4249708             0              0              0               0             0              0   1255488    6715840      1533767       1130531        688608        1361319      1162844             0             0              0                0                 0                 0                  0                0                 0
1         OSTO    e25yde7                20            1   Takedar            0          0           0             0              0              0               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0
2         OSTO    e25yde7                20            2      Jukk     19218242          0           0             0              0              0               0             0              0         0    1844741      1096022       1245824        985381         918034      5879375       7248862             0              0                0                 0                 0                  0                0                 0
3         OSTO    e25yde7                20            3      Jukk     19349413       3984           0             0         692508              0               0             0              0         0    6637156      1069809       7758546        954661        1124146       376840        731758             0              0                0                 0                 0                  0                0                 0
4         OSTO    e25yde7                20            4     Lojak            0          0           0             0              0              0               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0
..         ...        ...               ...          ...       ...          ...        ...         ...           ...            ...            ...             ...           ...            ...       ...        ...          ...           ...           ...            ...          ...           ...           ...            ...              ...               ...               ...                ...              ...               ...
387      一个复古风    y66xd7n                 8            3      Jukk            0          0           0             0              0              0               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0
388      一个复古风    y66xd7n                 8            4     Lojak            0          0           0             0              0              0               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0
389      一个复古风    y66xd7n                 8            5   Takedar            0          0           0             0              0              0               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0
390      一个复古风    y66xd7n                 8            6     Lojak      6112856          0           0        671270              0        5441586               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0
391      一个复古风    y66xd7n                 8            7   Takedar            0          0           0             0              0              0               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0

[392 rows x 30 columns]

In [18]:
db.session.rollback()

C:\Users\shush\Anaconda3\lib\site-packages\sqlalchemy\orm\session.py:561: SAWarning: Session's state has been changed on a non-active transaction - this state will be discarded.
  util.warn(

In [27]:
df1['TotalRaidAttacks'].max()

20

In [28]:
df1

    PlayerName PlayerCode  TotalRaidAttacks  TitanNumber TitanName  TitanDamage  ArmorHead  ArmorTorso  ArmorLeftArm  ArmorRightArm  ArmorLeftHand  ArmorRightHand  ArmorLeftLeg  ArmorRightLeg  BodyHead  BodyTorso  BodyLeftArm  BodyRightArm  BodyLeftHand  BodyRightHand  BodyLeftLeg  BodyRightLeg  SkeletonHead  SkeletonTorso  SkeletonLeftArm  SkeletonRightArm  SkeletonLeftHand  SkeletonRightHand  SkeletonLeftLeg  SkeletonRightLeg
0         OSTO    e25yde7                20            0   Takedar     18098110          0     4249708             0              0              0               0             0              0   1255488    6715840      1533767       1130531        688608        1361319      1162844             0             0              0                0                 0                 0                  0                0                 0
1         OSTO    e25yde7                20            1   Takedar            0          0           0             0              0              0               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0
2         OSTO    e25yde7                20            2      Jukk     19218242          0           0             0              0              0               0             0              0         0    1844741      1096022       1245824        985381         918034      5879375       7248862             0              0                0                 0                 0                  0                0                 0
3         OSTO    e25yde7                20            3      Jukk     19349413       3984           0             0         692508              0               0             0              0         0    6637156      1069809       7758546        954661        1124146       376840        731758             0              0                0                 0                 0                  0                0                 0
4         OSTO    e25yde7                20            4     Lojak            0          0           0             0              0              0               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0
..         ...        ...               ...          ...       ...          ...        ...         ...           ...            ...            ...             ...           ...            ...       ...        ...          ...           ...           ...            ...          ...           ...           ...            ...              ...               ...               ...                ...              ...               ...
387      一个复古风    y66xd7n                 8            3      Jukk            0          0           0             0              0              0               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0
388      一个复古风    y66xd7n                 8            4     Lojak            0          0           0             0              0              0               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0
389      一个复古风    y66xd7n                 8            5   Takedar            0          0           0             0              0              0               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0
390      一个复古风    y66xd7n                 8            6     Lojak      6112856          0           0        671270              0        5441586               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0
391      一个复古风    y66xd7n                 8            7   Takedar            0          0           0             0              0              0               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0

[392 rows x 30 columns]

In [23]:
df1['TitanNumber'].max()

7

In [31]:
df1.groupby("PlayerCode").count().shape[0]

49

In [44]:
bodys=['BodyHead', 'BodyTorso', 'BodyLeftArm', 'BodyRightArm', 'BodyLeftHand', 'BodyRightHand', 'BodyLeftLeg', 'BodyRightLeg']

In [54]:
no_attacks=df1.groupby(['TitanNumber','TitanName'])[bodys].sum()
no_attacks=no_attacks.reset_index()
no_attacks

   TitanNumber TitanName  BodyHead  BodyTorso  BodyLeftArm  BodyRightArm  BodyLeftHand  BodyRightHand  BodyLeftLeg  BodyRightLeg
0            0   Takedar  48052003   38572177      6373005       6949554       8436379        7288511      9541273      10949995
1            1   Takedar  40286989   51422452      8059509       9124995       9124998        7353175      9674963      10949986
2            2      Jukk         0   51099979     10229986      12208451      12774992       10137546     24856800      24700963
3            3      Jukk         0   51099979     12774990      12616788      11003234        8095024     25549983      25549987
4            4     Lojak  26697863   54985403     10563686             0       9592932        6119907     16868868      21713677
5            5   Takedar  28178008   59819487      9124987       9124990       9124991        9124992     13966632      11274778
6            6     Lojak  22493357   46845119     10949991             0      10949990       10949988     21899993      21899988
7            7   Takedar  36912940   52436974      9712435       9124984      11374878        9316922     10949981      10949984

In [57]:
df1

    PlayerName PlayerCode  TotalRaidAttacks  TitanNumber TitanName  TitanDamage  ArmorHead  ArmorTorso  ArmorLeftArm  ArmorRightArm  ArmorLeftHand  ArmorRightHand  ArmorLeftLeg  ArmorRightLeg  BodyHead  BodyTorso  BodyLeftArm  BodyRightArm  BodyLeftHand  BodyRightHand  BodyLeftLeg  BodyRightLeg  SkeletonHead  SkeletonTorso  SkeletonLeftArm  SkeletonRightArm  SkeletonLeftHand  SkeletonRightHand  SkeletonLeftLeg  SkeletonRightLeg
0         OSTO    e25yde7                20            1   Takedar            0          0           0             0              0              0               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0
1         OSTO    e25yde7                20            2      Jukk     19218242          0           0             0              0              0               0             0              0         0    1844741      1096022       1245824        985381         918034      5879375       7248862             0              0                0                 0                 0                  0                0                 0
2         OSTO    e25yde7                20            3      Jukk     19349413       3984           0             0         692508              0               0             0              0         0    6637156      1069809       7758546        954661        1124146       376840        731758             0              0                0                 0                 0                  0                0                 0
3         OSTO    e25yde7                20            4     Lojak            0          0           0             0              0              0               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0
4         OSTO    e25yde7                20            5   Takedar            0          0           0             0              0              0               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0
..         ...        ...               ...          ...       ...          ...        ...         ...           ...            ...            ...             ...           ...            ...       ...        ...          ...           ...           ...            ...          ...           ...           ...            ...              ...               ...               ...                ...              ...               ...
386      一个复古风    y66xd7n                 8            3      Jukk            0          0           0             0              0              0               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0
387      一个复古风    y66xd7n                 8            4     Lojak            0          0           0             0              0              0               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0
388      一个复古风    y66xd7n                 8            5   Takedar            0          0           0             0              0              0               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0
389      一个复古风    y66xd7n                 8            6     Lojak      6112856          0           0        671270              0        5441586               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0
390      一个复古风    y66xd7n                 8            7   Takedar            0          0           0             0              0              0               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0

[391 rows x 30 columns]

In [56]:
def add_new_CSVRules_instance(row):
    
    global each_csv_instances
    global player_name_t_new_instances
    body_TF=[True,True,True,True,True,True,True,True]
    body=['BodyHead', 'BodyTorso', 'BodyLeftArm', 'BodyRightArm', 'BodyLeftHand', 'BodyRightHand', 'BodyLeftLeg', 'BodyRightLeg']
    for i in range(len(body)):
        if row[body[i]]<=5000000:
            body_TF[i]=False
            
    if body_TF==[True,True,True,True,True,True,True,True]:
        return
    
    CSVRules_t_new_instance = CSVRules(      
        TitanNumber =row['TitanNumber'] ,
        TitanName =row['TitanName'] ,
        CSV_ID=csv_id,
        ArmorHead = body_TF[0],
        ArmorTorso = body_TF[1],
        ArmorLeftArm = body_TF[2],
        ArmorRightArm = body_TF[3],
        ArmorLeftHand = body_TF[4],
        ArmorRightHand = body_TF[5],
        ArmorLeftLeg = body_TF[6],
        ArmorRightLeg = body_TF[7],
    )

    each_csv_instances.append(player_name_t_new_instance)


no_attacks.apply(add_new_CSVRules_instance, axis=1, args=())

NameError: name 'CSVRules' is not defined

In [59]:
df=df1.copy()

In [60]:
df.columns

Index(['PlayerName', 'PlayerCode', 'TotalRaidAttacks', 'TitanNumber', 'TitanName', 'TitanDamage', 'ArmorHead', 'ArmorTorso', 'ArmorLeftArm', 'ArmorRightArm', 'ArmorLeftHand', 'ArmorRightHand', 'ArmorLeftLeg', 'ArmorRightLeg', 'BodyHead', 'BodyTorso', 'BodyLeftArm', 'BodyRightArm', 'BodyLeftHand', 'BodyRightHand', 'BodyLeftLeg', 'BodyRightLeg', 'SkeletonHead', 'SkeletonTorso', 'SkeletonLeftArm', 'SkeletonRightArm', 'SkeletonLeftHand', 'SkeletonRightHand', 'SkeletonLeftLeg', 'SkeletonRightLeg'], dtype='object')

In [61]:


armor = ['ArmorHead', 'ArmorTorso', 'ArmorLeftArm', 'ArmorRightArm', 'ArmorLeftHand', 'ArmorRightHand', 'ArmorLeftLeg', 'ArmorRightLeg']
body = ['BodyHead', 'BodyTorso', 'BodyLeftArm', 'BodyRightArm', 'BodyLeftHand', 'BodyRightHand', 'BodyLeftLeg', 'BodyRightLeg']
skeleton = ['SkeletonHead', 'SkeletonTorso', 'SkeletonLeftArm', 'SkeletonRightArm', 'SkeletonLeftHand', 'SkeletonRightHand', 'SkeletonLeftLeg', 'SkeletonRightLeg']

sum_Titian_Boday=df.groupby("TitanName").sum()[body]

In [62]:
sum_Titian_Boday

            BodyHead  BodyTorso  BodyLeftArm  BodyRightArm  BodyLeftHand  BodyRightHand  BodyLeftLeg  BodyRightLeg
TitanName
Jukk               0  102199958     23004976      24825239      23778226       18232570     50406783      50250950
Lojak       49191220  101830522     21513677             0      20542922       17069895     38768861      43613665
Takedar    153429940  202251090     33269936      34324523      38061246       33083600     44132849      44124743

In [63]:
grouped=np.where(sum_Titian_Boday==0)

In [64]:
grouped

(array([0, 1], dtype=int64), array([0, 3], dtype=int64))

In [66]:
zero_body=np.array(grouped).tolist()
zero_body

[[0, 1], [0, 3]]

In [67]:
list_sum_Titian_Boday_index=list(sum_Titian_Boday.index)
list_sum_Titian_Boday_index

['Jukk', 'Lojak', 'Takedar']

In [ ]:
list_sum_Titian_Boday_index=list(sum_Titian_Boday.index)
#print(list_sum_Titian_Boday_index)

titian_need_Zero=[]
for i in range(len(zero_body[0])):
    titian_need_Zero.append(list_sum_Titian_Boday_index[zero_body[0][i]])
#print(titian_need_Zero)

def wrong_function(row):
    #print(row['泰坦名称'])
    #print("===========================")
    if str(row['泰坦名称']) in titian_need_Zero:
        #print("我进if啦==================================================")
        num_titian=list_sum_Titian_Boday_index.index(row['泰坦名称'])
        #print(f"我是第{num_titian}个泰坦")
        wrong_dmg=0
        #遍历zero_body[0]，如果和num_titian一样，就累加，遍历结束，返回
        for i in range(len(zero_body[0])):
            if num_titian==i:
                wrong_dmg += row[armor[zero_body[1][i]]]
                #print(wrong_dmg)
        return wrong_dmg
    else:
        return 0



df["错误伤害"]=df.apply(wrong_function,axis=1,args=())

df["有效伤害"]=df["泰坦伤害"]-df["错误伤害"]

df_total=df.groupby(["玩家编号","玩家名称"]).sum()
df_total["突袭次数"]=df.groupby(["玩家编号","玩家名称"])["总突击伤害"].mean()
df_total["个人均伤"]=df_total["泰坦伤害"]/df_total["突袭次数"]
df_total["有效占比"]=round(df_total["有效伤害"]/df_total["泰坦伤害"]*100,2)

df_total['armor_total'] = round(df_total[armor].apply(lambda x : (x.sum()),axis=1 ),2)

df_total['body_total'] = round(df_total[body].apply(lambda x : (x.sum()),axis=1 ),2)

df_total['armor_total_per']=round((df_total['armor_total']/df_total["泰坦伤害"])*100,2)

df_total['body_total_per']=round((df_total['body_total']/df_total["泰坦伤害"])*100,2)

df_total["Rank_有效伤害"]=df_total["有效伤害"].rank(ascending=False).map(lambda x:int(x))
df_total["Rank_倒数次数"]=df_total["总突击伤害"].rank(ascending=True).map(lambda x:int(x))

df_f=df_total.drop(columns=['总突击伤害',"泰坦编号",'头部(装甲)', '身体(装甲)','左臂(装甲)', '右臂(装甲)', '左手(装甲)', '右手(装甲)', '左腿(装甲)', '右腿(装甲)',
                       '头部(肉体)','身体(肉体)', '左臂(肉体)', '右臂(肉体)', '左手(肉体)', '右手(肉体)', '左腿(肉体)', '右腿(肉体)',
                       '头部(骨架)', '身体(骨架)', '左臂(骨架)', '右臂(骨架)', '左手(骨架)', '右手(骨架)', '左腿(骨架)','右腿(骨架)' ])


list_columns_temp=list(df_f.columns)

timestamp=pd.Timestamp(file_year+"-"+file_month+"-"+file_day)

df_f.columns=[[timestamp]*len(list(df_f.columns)),list_columns_temp]


dataframe_lists.append(df_f)

In [70]:
df.groupby(["PlayerCode","TitanNumber"]).sum().reset_index()

    PlayerCode  TitanNumber  TotalRaidAttacks  TitanDamage  ArmorHead  ArmorTorso  ArmorLeftArm  ArmorRightArm  ArmorLeftHand  ArmorRightHand  ArmorLeftLeg  ArmorRightLeg  BodyHead  BodyTorso  BodyLeftArm  BodyRightArm  BodyLeftHand  BodyRightHand  BodyLeftLeg  BodyRightLeg  SkeletonHead  SkeletonTorso  SkeletonLeftArm  SkeletonRightArm  SkeletonLeftHand  SkeletonRightHand  SkeletonLeftLeg  SkeletonRightLeg
0      2ww84em            0                13            0          0           0             0              0              0               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0
1      2ww84em            1                13            0          0           0             0              0              0               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0
2      2ww84em            2                13            0          0           0             0              0              0               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0
3      2ww84em            3                13     20406253     527212    11597502        661444         418191         725952          543056       5555780         377113         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0
4      2ww84em            4                13            0          0           0             0              0              0               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0
..         ...          ...               ...          ...        ...         ...           ...            ...            ...             ...           ...            ...       ...        ...          ...           ...           ...            ...          ...           ...           ...            ...              ...               ...               ...                ...              ...               ...
386    yg8x58q            3                20            0          0           0             0              0              0               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0
387    yg8x58q            4                20     13719165    5852463      799935        579249              0         657167          929417        868225        4032705         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0
388    yg8x58q            5                20     13508558          0     7305675        268546        3175721         452449         1338956             0              0    238683          0            0             0             0              0       310381        418144             0              0                0                 0                 0                  0                0                 0
389    yg8x58q            6                20            0          0           0             0              0              0               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0
390    yg8x58q            7                20     13732434          0     8108677             0              0              0               0             0              0    872567          0       794407        764824        733530         894865       646080        917480             0              0                0                 0                 0                  0                0                 0

[391 rows x 28 columns]

In [ ]:
df['WrongDMG']

In [71]:
parts_sign=[[True, True, False, False, False, False, False, True, 0], [True, False, True, True, True, True, True, True, 1], [True, True, True, True, True, False, True, True, 2], [True, False, True, True, True, True, True, True, 3], [True, False, True, True, True, True, True, True, 4], [True, True, True, True, True, False, True, True, 5]]

In [ ]:
for i in parts_sign:
    if row['TitanNumber']==i[8]:
        for j in range(len(i)):
            if i[j]==False:

In [ ]:
def get_WrongDMG(row):
    armor=['ArmorHead','ArmorTorso', 'ArmorLeftArm', 'ArmorRightArm', 'ArmorLeftHand', 'ArmorRightHand', 'ArmorLeftLeg','ArmorRightLeg']
    WrongDMG_per_titan=0
    for i in parts_sign:
        if row['TitanNumber']==i[8]:
            for j in range(len(i)):
                if i[j]==False:
                    WrongDMG_per_titan+=row[armor[j]]
    return WrongDMG_per_titan

In [25]:
df1

    PlayerName PlayerCode  TotalRaidAttacks  TitanNumber TitanName  TitanDamage  ArmorHead  ArmorTorso  ArmorLeftArm  ArmorRightArm  ArmorLeftHand  ArmorRightHand  ArmorLeftLeg  ArmorRightLeg  BodyHead  BodyTorso  BodyLeftArm  BodyRightArm  BodyLeftHand  BodyRightHand  BodyLeftLeg  BodyRightLeg  SkeletonHead  SkeletonTorso  SkeletonLeftArm  SkeletonRightArm  SkeletonLeftHand  SkeletonRightHand  SkeletonLeftLeg  SkeletonRightLeg
0         OSTO    e25yde7                20            1   Takedar            0          0           0             0              0              0               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0
1         OSTO    e25yde7                20            2      Jukk     19218242          0           0             0              0              0               0             0              0         0    1844741      1096022       1245824        985381         918034      5879375       7248862             0              0                0                 0                 0                  0                0                 0
2         OSTO    e25yde7                20            3      Jukk     19349413       3984           0             0         692508              0               0             0              0         0    6637156      1069809       7758546        954661        1124146       376840        731758             0              0                0                 0                 0                  0                0                 0
3         OSTO    e25yde7                20            4     Lojak            0          0           0             0              0              0               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0
4         OSTO    e25yde7                20            5   Takedar            0          0           0             0              0              0               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0
..         ...        ...               ...          ...       ...          ...        ...         ...           ...            ...            ...             ...           ...            ...       ...        ...          ...           ...           ...            ...          ...           ...           ...            ...              ...               ...               ...                ...              ...               ...
386      一个复古风    y66xd7n                 8            3      Jukk            0          0           0             0              0              0               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0
387      一个复古风    y66xd7n                 8            4     Lojak            0          0           0             0              0              0               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0
388      一个复古风    y66xd7n                 8            5   Takedar            0          0           0             0              0              0               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0
389      一个复古风    y66xd7n                 8            6     Lojak      6112856          0           0        671270              0        5441586               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0
390      一个复古风    y66xd7n                 8            7   Takedar            0          0           0             0              0              0               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0

[391 rows x 30 columns]

In [31]:
summm=df1.groupby("PlayerCode").sum().reset_index()

In [20]:
df1[df1["PlayerCode"]=="x67y9yq"]['TotalRaidAttacks'].max()

16

In [30]:
(df1['TitanNumber'].max()+1)

8

In [36]:
summm['TotalRaidAttacks'].rank(method='max')

0     15.0
1     38.0
2     49.0
3      7.0
4     13.0
5     38.0
6     38.0
7     38.0
8     49.0
9     38.0
10    38.0
11     7.0
12    38.0
13    49.0
14     8.0
15    49.0
16    38.0
17    13.0
18    49.0
19    38.0
20     7.0
21    38.0
22    13.0
23    49.0
24    38.0
25    13.0
26    38.0
27    39.0
28    38.0
29    16.0
30     7.0
31    15.0
32    38.0
33    38.0
34    38.0
35    38.0
36    13.0
37    49.0
38     7.0
39    49.0
40    49.0
41    38.0
42    38.0
43    38.0
44    38.0
45    38.0
46     7.0
47     7.0
48    49.0
Name: TotalRaidAttacks, dtype: float64

In [23]:
df1_sum=pd.read_csv("df1_sum.csv")

In [24]:
df1_sum

    Unnamed: 0 PlayerCode  TotalRaidAttacks  TitanNumber  TitanDamage  ArmorHead  ArmorTorso  ArmorLeftArm  ArmorRightArm  ArmorLeftHand  ArmorRightHand  ArmorLeftLeg  ArmorRightLeg  BodyHead  BodyTorso  BodyLeftArm  BodyRightArm  BodyLeftHand  BodyRightHand  BodyLeftLeg  BodyRightLeg  SkeletonHead  SkeletonTorso  SkeletonLeftArm  SkeletonRightArm  SkeletonLeftHand  SkeletonRightHand  SkeletonLeftLeg  SkeletonRightLeg  WrongDMG  EffectiveDMG
0            0    2ww84em                18           15     38995323   10005979     1956274             0        4720108              0            2007       8493267        3910065   2850135    5105646            0             0             0              0      1951837             0             0              0                0                 0                 0                  0                0                 0       495      38994828
1            1    3239p74                22           15     19402162    1655413     1321727        354759              0         240073               0             0              0   2797879    4688909      3624245          8980       2568274         875683            0       1266214             0              0                0                 0                 0                  0                0                 0      3400      19398762
2            2    32d47b9                21           15     23179525    3175433     1513117        272898              0         367318               0             0         321613   2763756    1913756      6130226       1785714       3470751              0      1216540        246777           707              0              912                 0                 0                  0                0                 0     47854      23131671
3            3    36xq4qw                 0           15            0          0           0             0              0              0               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0         0             0
4            4    3nw4q8n                17           15     22167024    3535549     1578392             0        1455046              0          923912             0        1217089   4944732    4692779         3186             0             0              0       953556       2862495           280              0                0                 0                 0                  0                0                 0      6573      22160451
5            5    523dqmp                24           15     35999852          0           0             0              0              0               0             0              0   2734301    5472630            0             0       4111867        2027178     12512853       9141018             0              0                0                 0                 0                  0                0                 0         0      35999852
6            6    52ymnnk                20           15     23847148    1097776     1080452             0              0              0         1805338             0        2380991   6533925    3607710      2573619             0       1738137        1018140            0       2011052             0              0                0                 0                 0                  0                0                 0         0      23847148
7            7    6567qp8                24           15     22893584    4697429      787426       1014893         148864              0          634650       3067845        6813673    819544     845391            0             0             0         199803       947807       2916252             0              0                0                 0                 0                  0                0                 0         0      22893584
8            8    6r922bx                20           15     30919164    5313448        8189             0              0         265884               0       1048948        2623635   9795184    3072821      3860185       4908826         21593              0            0             0           383              0                0                 0                 0                 63                0                 0      8189      30910975
9            9     6rpd3e                17           15     43216816    8869993     5451395        106731        2170053        2030298            1948       2608479       14401734   2894905    2600587            0             0             0        2080687            0             0             0              0                0                 0                 0                  0                0                 0      1807      43215009
10          10    87ee6rw                19           15     27242327    2052164     2337816       4268615              0        1604567               0       1188412        1004358         0    3466659      1339052             0             0              0      7861658       2119021             0              0                0                 0                 0                  0                0                 0         0      27242327
11          11    9ede8xe                18           15     31583297    1648208     4372580             0              0              0               0             0        3248639   5466275   12436550            0             0             0              0      2981307       1429572           161              0                0                 0                 0                  0                0                 0         0      31583297
12          12    b2rmkk3                16           15     33234542    1491266           0        470584         650968              0             574       3564179        4193614  13058290    5375375      1526543             0        351049        1493359       644418        413916            47              0                0                 0                 0                  0                0               353       574      33233968
13          13    b65mrx8                24           15     31920285    3303327      562692       1692167        2393685        2649505               0       4927609        1559382   1060233    3299962       143823        392638        379422         696159      6276369       2583297             0              0                0                 0                 0                  0                0                 0     25988      31894297
14          14    b6667p5                20           15     36865694    1542746     4437881       5270945        1449915        1664174          846164       6020584        3951741   2850425    5731330            0             0       1343176        1421303       297572         37724             0              0                0                 0                 0                  0                0                 0         0      36865694
15          15    d234wb5                24           15     35700137    3868824      170991             0        1589975         804502         1274965             0              0   6840309    2663884      1438231       3594564       1364881        2658506      5967761       3461062             0            321               38                 0                 0                  0             1317                 0    170991      35529146
16          16    d2w7rmg                16           15     29629752    6497766     4293458       1524901              0              0               0             0              0  11831576    1215971      1383992       1596825        960826         318739            0             0          4884              0              808                 0                 0                  0                0                 0   2669087      26960665
17          17    dmne2qx                19           15     23421308    4196481           0             0         245422              0               0        256427         260229         0     754443      2985804             0       3949464         275705      3065286       7431878             0              0               33                 0               126                  0                0                 0         0      23421308
18          18    e4w4gp8                24           15     23983735    3477759        9863        184323        1675836        2262143          793453        609126         188794   5675552    4989770      1156344        299766        113668         242467      2300539             0           292              0             2934              1092                 0                  0                0                 0     10083      23973652
19          19    g98r5en                24           15     43327227    1330979     3227037        595435        3575660         637164         1502521             0        1934579   4492552    5606169      3122310       4782728        720017        4454162      6265781       1080122             0              0                0                 0                 0                  0                0                 0         0      43327227
20          20    g9r74w8                20           15     38860559    1592995     8699179             0              0         967444         1717398           775        2342386   9536097          0            0             0       3110744         155906       750924       9986409             0              0                0                 0                 0                147                0               147         0      38860559
21          21    gmyr876                15           15     27598194    3444157     3114738             0              0              0         3276081             0        5315308  10439578    2008326            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0    313433      27284761
22          22    gybwkyk                24           15     27540778    3004665     3755449             0              0        2811615            2630        852177         924859         0    5611455            0             0       6212348        2948412      1416910             0             0              0                0                 0               249                  0                0                 0      2630      27538148
23          23    k89y65p                20           15     37628315   13300459     4323845             0              0              0             452       8861302              0   4403261    2490254            0       2509722             0              0       587483       1150666            22              0                0               304                 0                  0              270               270   1404467      36223848
24          24    km9dbm9                20           15     24747716     977476     3216181       1147290          45824         137108            2536        171374         177783         0    3233436      1127096        118594        186275        1492533      1739204      10974997             0              0                0                 0                 0                  0                0                 0   1014648      23733068
25          25    md72p6d                12           15     17620019    3923939           0             0              0              0          844947             0        5304920   4091108          0      1144649             0         25285        2285167            0             0             0              0                0                 0                 0                  0                0                 0         0      17620019
26          26    mng2634                19           15     37237770   11208462     1780657       1039196              0        3518931               0             0              0   4553710    5899553      3328281             0         60942              0         1995       5846037             0              0                0                 0                 0                  0                0                 0         0      37237770
27          27    ng64n3n                16           15     34503694          0           0       1422271        1528052        3848793         5322913             0              0   2998706    4753818            0       3105019       5296618         499161      5551775        174869             0              0                0                 0              1694                  0                0                 0         0      34503694
28          28    ny32m8q                15           15     16353742    2417385     3369298       2433635         356580         692198               0             0        1872812    515337    1295774       106319        201977             0              0            0       3089640          2780              0                0                 0                 0                  0                0                 0    863685      15490057
29          29     p2dbk3                20           15     32073409    5819590     1512455          2839        1124044         241133               0       1083908              0   8842140    5001620            0       1260679       4788779              0        34248       2361965             0              0                0                 0                 0                  0                0                 0         0      32073409
30          30    p53g24x                15           15     20825372    3257623     2217061           393        1906758        1192827               0       3199431        2781126   4003840    2266308            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0         0      20825372
31          31    p7dygdn                16           15     20957113    1773702           0             0              0        5916457               0       1568770              0    954167    2849018            0             0       1474513        1962981       338579       4118701             0              0                0                 0                 0                218                0                 0         0      20957113
32          32    p7k86mx                16           15     28998204    1593737     5534082       1717993          13438              0         2915039             0        2208010   1319904          0            0       4247144             0        1288962      3154021       5005531             0              0                0                 0                 0                 88                0               248         0      28998204
33          33    p7qkn7y                16           15     26254999    5453612     5518175       1355991              0              0         1359046             0              0   8786766    2477933            0             0             0              0            0       1303473             0              0                0                 0                 0                  0                0                 0         0      26254999
34          34    q4kkbmk                23           15     55672512    4495836           0       7885659        6246682          12935               0             0         260229   4408729    2059246      3557712       6062132       1921103        8405732            0      10356378             0              0               73                54                 0                  0                0                 0         0      55672512
35          35    qk53q63                20           15     18451776    6472726     1971476             0              0           2355             160        833509        2008506    655371    2780507            0             0             0              0      2461146       1266016             0              0                0                 0                 0                  0                0                 0       160      18451616
36          36    qm2n54y                20           15     37346530    6204237     1529946       1901364        1395143        1792884          385886       5724349              0   6044195    3809752            0       1811040       4196621          31184      2519533             0             0              0                0                 0               393                  0                0                 0     25587      37320943
37          37    qq52rrr                20           15     21221798     777889     3459604             0              0              0               0       2691591        1766203   1655996     845457      3588222       3326422        549467         974206       359588       1227132             0              0                0                 0                 0                 16                0                 0         0      21221798
38          38    r5948nw                20           15     20409702    9181149     2437615             0         554825              0          303601       3076400        2038655   2137345     680108            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0    753819      19655883
39          39    r5xpnx5                20           15     29279143    4747262         761             0              0            251         1175409       2317206        2652711   4478262    1226616            0             0           453        2481105      3519608       6679493             0              0                0                 0                 0                  0                0                 0       761      29278382
40          40    rm7ngpr                19           15     34620444    2170280     1569661             0              0              0               0       1398743              0   2717300    5367997            0       5448899             0        1677590            0      14269922             0              0                0                 0                 0                 48                0                 0       452      34619992
41          41    rmn4k2r                17           15     29584910    4468297     2146123             0              0         244168          649963        149678              0   8012677    8083205      4358008        203713             0              0      1267902             0             0              0              167              1006                 0                  0                0                 0    649963      28934947
42          42    rq349xd                20           15     43113031   10631044     4563123       1532321        5278092              0               0             0        1614543  14383164    3043835      2066906             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0         0      43113031

In [29]:
    df1_sum['EffectiveDMG_Rank']=df1['EffectiveDMG'].rank(method='max',ascending=False)
    df1_sum['EffectiveDMG_RankFromLast'] = df1['EffectiveDMG'].rank(method='max')
    df1_sum['RaidAttacks_RankFromLast'] = df1['TotalRaidAttacks'].rank(method='max')

In [30]:
df1_sum

    Unnamed: 0 PlayerCode  TotalRaidAttacks  TitanNumber  TitanDamage  ArmorHead  ArmorTorso  ArmorLeftArm  ArmorRightArm  ArmorLeftHand  ArmorRightHand  ArmorLeftLeg  ArmorRightLeg  BodyHead  BodyTorso  BodyLeftArm  BodyRightArm  BodyLeftHand  BodyRightHand  BodyLeftLeg  BodyRightLeg  SkeletonHead  SkeletonTorso  SkeletonLeftArm  SkeletonRightArm  SkeletonLeftHand  SkeletonRightHand  SkeletonLeftLeg  SkeletonRightLeg  WrongDMG  EffectiveDMG  EffectiveDMG_Rank  EffectiveDMG_RankFromLast  RaidAttacks_RankFromLast
0            0    2ww84em                18           15     38995323   10005979     1956274             0        4720108              0            2007       8493267        3910065   2850135    5105646            0             0             0              0      1951837             0             0              0                0                 0                 0                  0                0                 0       495      38994828                6.0                       44.0                      19.0
1            1    3239p74                22           15     19402162    1655413     1321727        354759              0         240073               0             0              0   2797879    4688909      3624245          8980       2568274         875683            0       1266214             0              0                0                 0                 0                  0                0                 0      3400      19398762               43.0                        7.0                      40.0
2            2    32d47b9                21           15     23179525    3175433     1513117        272898              0         367318               0             0         321613   2763756    1913756      6130226       1785714       3470751              0      1216540        246777           707              0              912                 0                 0                  0                0                 0     47854      23131671               35.0                       15.0                      39.0
3            3    36xq4qw                 0           15            0          0           0             0              0              0               0             0              0         0          0            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0         0             0               49.0                        1.0                       1.0
4            4    3nw4q8n                17           15     22167024    3535549     1578392             0        1455046              0          923912             0        1217089   4944732    4692779         3186             0             0              0       953556       2862495           280              0                0                 0                 0                  0                0                 0      6573      22160451               37.0                       13.0                      17.0
5            5    523dqmp                24           15     35999852          0           0             0              0              0               0             0              0   2734301    5472630            0             0       4111867        2027178     12512853       9141018             0              0                0                 0                 0                  0                0                 0         0      35999852               13.0                       37.0                      49.0
6            6    52ymnnk                20           15     23847148    1097776     1080452             0              0              0         1805338             0        2380991   6533925    3607710      2573619             0       1738137        1018140            0       2011052             0              0                0                 0                 0                  0                0                 0         0      23847148               32.0                       18.0                      38.0
7            7    6567qp8                24           15     22893584    4697429      787426       1014893         148864              0          634650       3067845        6813673    819544     845391            0             0             0         199803       947807       2916252             0              0                0                 0                 0                  0                0                 0         0      22893584               36.0                       14.0                      49.0
8            8    6r922bx                20           15     30919164    5313448        8189             0              0         265884               0       1048948        2623635   9795184    3072821      3860185       4908826         21593              0            0             0           383              0                0                 0                 0                 63                0                 0      8189      30910975               21.0                       29.0                      38.0
9            9     6rpd3e                17           15     43216816    8869993     5451395        106731        2170053        2030298            1948       2608479       14401734   2894905    2600587            0             0             0        2080687            0             0             0              0                0                 0                 0                  0                0                 0      1807      43215009                4.0                       46.0                      17.0
10          10    87ee6rw                19           15     27242327    2052164     2337816       4268615              0        1604567               0       1188412        1004358         0    3466659      1339052             0             0              0      7861658       2119021             0              0                0                 0                 0                  0                0                 0         0      27242327               28.0                       22.0                      23.0
11          11    9ede8xe                18           15     31583297    1648208     4372580             0              0              0               0             0        3248639   5466275   12436550            0             0             0              0      2981307       1429572           161              0                0                 0                 0                  0                0                 0         0      31583297               20.0                       30.0                      19.0
12          12    b2rmkk3                16           15     33234542    1491266           0        470584         650968              0             574       3564179        4193614  13058290    5375375      1526543             0        351049        1493359       644418        413916            47              0                0                 0                 0                  0                0               353       574      33233968               17.0                       33.0                      14.0
13          13    b65mrx8                24           15     31920285    3303327      562692       1692167        2393685        2649505               0       4927609        1559382   1060233    3299962       143823        392638        379422         696159      6276369       2583297             0              0                0                 0                 0                  0                0                 0     25988      31894297               19.0                       31.0                      49.0
14          14    b6667p5                20           15     36865694    1542746     4437881       5270945        1449915        1664174          846164       6020584        3951741   2850425    5731330            0             0       1343176        1421303       297572         37724             0              0                0                 0                 0                  0                0                 0         0      36865694               11.0                       39.0                      38.0
15          15    d234wb5                24           15     35700137    3868824      170991             0        1589975         804502         1274965             0              0   6840309    2663884      1438231       3594564       1364881        2658506      5967761       3461062             0            321               38                 0                 0                  0             1317                 0    170991      35529146               14.0                       36.0                      49.0
16          16    d2w7rmg                16           15     29629752    6497766     4293458       1524901              0              0               0             0              0  11831576    1215971      1383992       1596825        960826         318739            0             0          4884              0              808                 0                 0                  0                0                 0   2669087      26960665               29.0                       21.0                      14.0
17          17    dmne2qx                19           15     23421308    4196481           0             0         245422              0               0        256427         260229         0     754443      2985804             0       3949464         275705      3065286       7431878             0              0               33                 0               126                  0                0                 0         0      23421308               34.0                       16.0                      23.0
18          18    e4w4gp8                24           15     23983735    3477759        9863        184323        1675836        2262143          793453        609126         188794   5675552    4989770      1156344        299766        113668         242467      2300539             0           292              0             2934              1092                 0                  0                0                 0     10083      23973652               31.0                       19.0                      49.0
19          19    g98r5en                24           15     43327227    1330979     3227037        595435        3575660         637164         1502521             0        1934579   4492552    5606169      3122310       4782728        720017        4454162      6265781       1080122             0              0                0                 0                 0                  0                0                 0         0      43327227                3.0                       47.0                      49.0
20          20    g9r74w8                20           15     38860559    1592995     8699179             0              0         967444         1717398           775        2342386   9536097          0            0             0       3110744         155906       750924       9986409             0              0                0                 0                 0                147                0               147         0      38860559                7.0                       43.0                      38.0
21          21    gmyr876                15           15     27598194    3444157     3114738             0              0              0         3276081             0        5315308  10439578    2008326            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0    313433      27284761               27.0                       23.0                       7.0
22          22    gybwkyk                24           15     27540778    3004665     3755449             0              0        2811615            2630        852177         924859         0    5611455            0             0       6212348        2948412      1416910             0             0              0                0                 0               249                  0                0                 0      2630      27538148               26.0                       24.0                      49.0
23          23    k89y65p                20           15     37628315   13300459     4323845             0              0              0             452       8861302              0   4403261    2490254            0       2509722             0              0       587483       1150666            22              0                0               304                 0                  0              270               270   1404467      36223848               12.0                       38.0                      38.0
24          24    km9dbm9                20           15     24747716     977476     3216181       1147290          45824         137108            2536        171374         177783         0    3233436      1127096        118594        186275        1492533      1739204      10974997             0              0                0                 0                 0                  0                0                 0   1014648      23733068               33.0                       17.0                      38.0
25          25    md72p6d                12           15     17620019    3923939           0             0              0              0          844947             0        5304920   4091108          0      1144649             0         25285        2285167            0             0             0              0                0                 0                 0                  0                0                 0         0      17620019               47.0                        3.0                       3.0
26          26    mng2634                19           15     37237770   11208462     1780657       1039196              0        3518931               0             0              0   4553710    5899553      3328281             0         60942              0         1995       5846037             0              0                0                 0                 0                  0                0                 0         0      37237770               10.0                       40.0                      23.0
27          27    ng64n3n                16           15     34503694          0           0       1422271        1528052        3848793         5322913             0              0   2998706    4753818            0       3105019       5296618         499161      5551775        174869             0              0                0                 0              1694                  0                0                 0         0      34503694               16.0                       34.0                      14.0
28          28    ny32m8q                15           15     16353742    2417385     3369298       2433635         356580         692198               0             0        1872812    515337    1295774       106319        201977             0              0            0       3089640          2780              0                0                 0                 0                  0                0                 0    863685      15490057               48.0                        2.0                       7.0
29          29     p2dbk3                20           15     32073409    5819590     1512455          2839        1124044         241133               0       1083908              0   8842140    5001620            0       1260679       4788779              0        34248       2361965             0              0                0                 0                 0                  0                0                 0         0      32073409               18.0                       32.0                      38.0
30          30    p53g24x                15           15     20825372    3257623     2217061           393        1906758        1192827               0       3199431        2781126   4003840    2266308            0             0             0              0            0             0             0              0                0                 0                 0                  0                0                 0         0      20825372               41.0                        9.0                       7.0
31          31    p7dygdn                16           15     20957113    1773702           0             0              0        5916457               0       1568770              0    954167    2849018            0             0       1474513        1962981       338579       4118701             0              0                0                 0                 0                218                0                 0         0      20957113               40.0                       10.0                      14.0
32          32    p7k86mx                16           15     28998204    1593737     5534082       1717993          13438              0         2915039             0        2208010   1319904          0            0       4247144             0        1288962      3154021       5005531             0              0                0                 0                 0                 88                0               248         0      28998204               24.0                       26.0                      14.0
33          33    p7qkn7y                16           15     26254999    5453612     5518175       1355991              0              0         1359046             0              0   8786766    2477933            0             0             0              0            0       1303473             0              0                0                 0                 0                  0                0                 0         0      26254999               30.0                       20.0                      14.0
34          34    q4kkbmk                23           15     55672512    4495836           0       7885659        6246682          12935               0             0         260229   4408729    2059246      3557712       6062132       1921103        8405732            0      10356378             0              0               73                54                 0                  0                0                 0         0      55672512                1.0                       49.0                      42.0
35          35    qk53q63                20           15     18451776    6472726     1971476             0              0           2355             160        833509        2008506    655371    2780507            0             0             0              0      2461146       1266016             0              0                0                 0                 0                  0                0                 0       160      18451616               45.0                        5.0                      38.0
36          36    qm2n54y                20           15     37346530    6204237     1529946       1901364        1395143        1792884          385886       5724349              0   6044195    3809752            0       1811040       4196621          31184      2519533             0             0              0                0                 0               393                  0                0                 0     25587      37320943                9.0                       41.0                      38.0